USE [master]
GO

/****** Object:  Database [DM_CodeChallenge]    Script Date: 27/03/2019 11:33:50 ******/
CREATE DATABASE [DM_CodeChallenge]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DM_CodeChallenge', FILENAME = N'D:\Aplicativos\SQL\MSSQL14.MSSQLSERVER\MSSQL\DATA\DM_CodeChallenge.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DM_CodeChallenge_log', FILENAME = N'D:\Aplicativos\SQL\MSSQL14.MSSQLSERVER\MSSQL\DATA\DM_CodeChallenge_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DM_CodeChallenge] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DM_CodeChallenge].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DM_CodeChallenge] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET ARITHABORT OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DM_CodeChallenge] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DM_CodeChallenge] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DM_CodeChallenge] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DM_CodeChallenge] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET RECOVERY FULL 
GO

ALTER DATABASE [DM_CodeChallenge] SET  MULTI_USER 
GO

ALTER DATABASE [DM_CodeChallenge] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DM_CodeChallenge] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DM_CodeChallenge] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DM_CodeChallenge] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DM_CodeChallenge] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DM_CodeChallenge] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DM_CodeChallenge] SET  READ_WRITE 
GO


